#spring:
#  application:
#    name: bus-ticket-ui
#
#app:
#  backend:
#    # Change this to wherever your `busbooking` backend is running.
#    # Examples: http://localhost:8080 or http://localhost:8081
#    base-url: "http://localhost:8082"
spring:
  application:
    name: bus-ticket-ui

server:
  port: 8089

app:
  backend:
    base-url: "http://localhost:8082"