package com.cg.busticketui.dto.response;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Data Transfer Object (DTO) for representing agency revenue details.
 * This DTO is used to send aggregated revenue information of an agency
 * from the backend to the client.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AgencyRevenueDto {

    /**
     * Unique identifier of the agency.
     */
    private Integer agencyId;

    /**
     * Name of the agency.
     */
    private String agencyName;

    /**
     * Total revenue generated by the agency.
     */
    private Double revenue;
}